CREATE TABLE Person
(
    person_id     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     varchar(100) NOT NULL UNIQUE,
    date_of_birth DATE,
    email         varchar(30)  NOT NULL UNIQUE,
    contact_phone varchar(13) CHECK (length(contact_phone) = 13)
);

CREATE TABLE Book
(
    book_id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(100) NOT NULL UNIQUE,
    author          varchar(100) NOT NULL,
    year_of_publish int,
    person_id       int          REFERENCES Person (person_id) ON DELETE SET NULL,
    borrowed_time   TIMESTAMP
);