CREATE TABLE Person
(
    person_id     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     varchar(100) NOT NULL UNIQUE,
    year_of_birth int CHECK ( year_of_birth > 1900 )
);

CREATE TABLE BOOK
(
    book_id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(100) NOT NULL UNIQUE,
    author          varchar(100) NOT NULL,
    year_of_publish int,
    person_id       int          REFERENCES Person (person_id) ON DELETE SET NULL
);